language: c

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ondrej/autotools -y
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake-1.15 pkg-config m4 libsndfile-dev libjack-dev libfftw3-dev libcairo2-dev libsamplerate0-dev

script:
  - ./autogen.sh
  - ./configure
  - make distcheck
